import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SlowNav } from "./slow-nav";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense
          fallback={
            <div className="bg-foreground p-4 w-full h-10 text-white">
              Slow naw loading...
            </div>
          }
        >
          <SlowNav />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
